"""add municipal zoning fields

Revision ID: 68752a5180b9
Revises: c7060d8466e3
Create Date: 2026-09-03 20:44:02.239523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68752a5180b9'
down_revision = 'c7060d8466e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zoning_source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('zoning_detail', sa.JSON(), nullable=True))
        # Widened for full municipal zoning strings, which carry overlay
        # suffixes the old 30 chars couldn't always hold (e.g.
        # 'SF-3-HD-NCCD-NP'). Widening never truncates existing values.
        batch_op.alter_column('property_zoning',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('property_lookup_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipal_zoning_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('municipal_zoning_source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('municipal_zoning_detail', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_lookup_cache', schema=None) as batch_op:
        batch_op.drop_column('municipal_zoning_detail')
        batch_op.drop_column('municipal_zoning_source')
        batch_op.drop_column('municipal_zoning_code')

    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.alter_column('property_zoning',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('zoning_detail')
        batch_op.drop_column('zoning_source')

    # ### end Alembic commands ###
