"""add property_sale_history to analysis

Revision ID: 7c86845236af
Revises: e92e94ab5ddb
Create Date: 2026-08-29 17:06:16.204092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c86845236af'
down_revision = 'e92e94ab5ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_sale_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_column('property_sale_history')

    # ### end Alembic commands ###
