"""add property_latitude and property_longitude to analysis

Revision ID: 88bc469d8e09
Revises: 7c86845236af
Create Date: 2026-08-29 23:09:21.544122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bc469d8e09'
down_revision = '7c86845236af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('property_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_column('property_longitude')
        batch_op.drop_column('property_latitude')

    # ### end Alembic commands ###
