"""initial schema

Revision ID: 9c27540fae18
Revises: 
Create Date: 2026-08-13 16:28:56.878718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c27540fae18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_lookup_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_address', sa.String(length=255), nullable=False),
    sa.Column('raw_property_json', sa.JSON(), nullable=True),
    sa.Column('raw_avm_json', sa.JSON(), nullable=True),
    sa.Column('raw_comps_json', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_address')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('property_sqft', sa.Integer(), nullable=True),
    sa.Column('property_bedrooms', sa.Integer(), nullable=True),
    sa.Column('property_bathrooms', sa.Float(), nullable=True),
    sa.Column('property_year_built', sa.Integer(), nullable=True),
    sa.Column('arv_estimate', sa.Float(), nullable=True),
    sa.Column('arv_method', sa.String(length=30), nullable=True),
    sa.Column('arv_confidence_low', sa.Float(), nullable=True),
    sa.Column('arv_confidence_high', sa.Float(), nullable=True),
    sa.Column('arv_comps_count', sa.Integer(), nullable=True),
    sa.Column('arv_comps_snapshot', sa.JSON(), nullable=True),
    sa.Column('reno_cost_estimate', sa.Float(), nullable=True),
    sa.Column('reno_cost_breakdown', sa.JSON(), nullable=True),
    sa.Column('holding_period_months', sa.Integer(), nullable=True),
    sa.Column('agent_commission_pct', sa.Float(), nullable=True),
    sa.Column('closing_costs_pct', sa.Float(), nullable=True),
    sa.Column('projected_net_profit', sa.Float(), nullable=True),
    sa.Column('projected_margin_pct', sa.Float(), nullable=True),
    sa.Column('flip_score', sa.Integer(), nullable=True),
    sa.Column('flip_grade', sa.String(length=30), nullable=True),
    sa.Column('flip_score_breakdown', sa.JSON(), nullable=True),
    sa.Column('llm_model', sa.String(length=60), nullable=True),
    sa.Column('llm_recommendation', sa.String(length=30), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('llm_risk_flags', sa.JSON(), nullable=True),
    sa.Column('llm_raw_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis')
    op.drop_table('user')
    op.drop_table('property_lookup_cache')
    # ### end Alembic commands ###
