"""drop raw_comps_json from property_lookup_cache

Revision ID: a7408baf8b0c
Revises: a6805f314685
Create Date: 2026-08-27 15:51:31.996784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a7408baf8b0c'
down_revision = 'a6805f314685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_lookup_cache', schema=None) as batch_op:
        batch_op.drop_column('raw_comps_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_lookup_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_comps_json', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
