"""add source to property_lookup_cache

Revision ID: c7060d8466e3
Revises: 88bc469d8e09
Create Date: 2026-08-30 13:54:05.872682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7060d8466e3'
down_revision = '88bc469d8e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_lookup_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), server_default='full_lookup', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_lookup_cache', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
