"""rewrite analysis table to match teardown-rebuild data model

Revision ID: e92e94ab5ddb
Revises: a7408baf8b0c
Create Date: 2026-08-28 11:22:07.887815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e92e94ab5ddb'
down_revision = 'a7408baf8b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        # server_default backfills any existing rows so this NOT NULL add
        # doesn't fail on a non-empty table (nothing constructs an
        # Analysis anywhere yet, so today this only matters in theory —
        # but the next migration to touch this table won't get that luxury).
        # Dropped again below once the backfill has happened.
        batch_op.add_column(sa.Column('initial_cost_per_sqft', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('initial_profit_margin_pct', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('property_lot_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('property_zoning', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('property_subdivision', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('market_value_estimate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('market_value_method', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('market_value_confidence', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('market_value_comps_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('market_value_comps_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('build_cost_estimate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cost_estimate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('required_sale_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('achievable_margin_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_worth_it', sa.Boolean(), nullable=True))
        batch_op.drop_column('reno_cost_breakdown')
        batch_op.drop_column('reno_cost_estimate')
        batch_op.drop_column('projected_margin_pct')
        batch_op.drop_column('arv_comps_snapshot')
        batch_op.drop_column('agent_commission_pct')
        batch_op.drop_column('llm_model')
        batch_op.drop_column('flip_score_breakdown')
        batch_op.drop_column('llm_recommendation')
        batch_op.drop_column('llm_raw_response')
        batch_op.drop_column('llm_summary')
        batch_op.drop_column('projected_net_profit')
        batch_op.drop_column('arv_estimate')
        batch_op.drop_column('flip_score')
        batch_op.drop_column('arv_confidence_low')
        batch_op.drop_column('closing_costs_pct')
        batch_op.drop_column('arv_method')
        batch_op.drop_column('llm_risk_flags')
        batch_op.drop_column('holding_period_months')
        batch_op.drop_column('arv_confidence_high')
        batch_op.drop_column('arv_comps_count')
        batch_op.drop_column('flip_grade')
        batch_op.drop_column('condition_notes')

    # ### end Alembic commands ###

    # Drop the temporary defaults now that any existing rows are backfilled
    # — the app always supplies both fields when creating an Analysis, so
    # new inserts shouldn't be able to silently omit them and get 0.
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.alter_column('initial_cost_per_sqft', server_default=None)
        batch_op.alter_column('initial_profit_margin_pct', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('flip_grade', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('arv_comps_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('arv_confidence_high', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('holding_period_months', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('llm_risk_flags', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('arv_method', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('closing_costs_pct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('arv_confidence_low', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('flip_score', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('arv_estimate', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('projected_net_profit', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('llm_summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('llm_raw_response', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('llm_recommendation', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('flip_score_breakdown', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('llm_model', sa.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('agent_commission_pct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('arv_comps_snapshot', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('projected_margin_pct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('reno_cost_estimate', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('reno_cost_breakdown', sqlite.JSON(), nullable=True))
        batch_op.drop_column('is_worth_it')
        batch_op.drop_column('achievable_margin_pct')
        batch_op.drop_column('required_sale_price')
        batch_op.drop_column('total_cost_estimate')
        batch_op.drop_column('build_cost_estimate')
        batch_op.drop_column('market_value_comps_snapshot')
        batch_op.drop_column('market_value_comps_count')
        batch_op.drop_column('market_value_confidence')
        batch_op.drop_column('market_value_method')
        batch_op.drop_column('market_value_estimate')
        batch_op.drop_column('property_subdivision')
        batch_op.drop_column('property_zoning')
        batch_op.drop_column('property_lot_size')
        batch_op.drop_column('initial_profit_margin_pct')
        batch_op.drop_column('initial_cost_per_sqft')

    # ### end Alembic commands ###
